# Generated by Django 3.2.4 on 2021-06-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(default='SOME STRING', max_length=30)),
                ('Cedula', models.CharField(default='SOME STRING', max_length=30)),
                ('Email', models.EmailField(default='SOME STRING', max_length=30)),
                ('Telefono', models.CharField(default='SOME STRING', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_de_Cuenta', models.IntegerField()),
                ('Saldo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Fecha_Creacion', models.DateField()),
                ('Tipo', models.IntegerField(choices=[(1, 'Ahorro'), (2, 'Corriente')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_de_Cuenta', models.IntegerField()),
                ('Tipo', models.IntegerField(choices=[(1, 'Deposito'), (2, 'Retiro')], default=1)),
                ('Fecha', models.DateField()),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
