# Generated by Django 3.2.4 on 2021-06-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajaDeAhorros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Cedula',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(default='', max_length=30),
        ),
    ]
