# Generated by Django 3.2.4 on 2021-06-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CajaDeAhorros', '0003_auto_20210630_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='Fecha_Creacion',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='Propietario',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='idCliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CajaDeAhorros.cliente'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='idCuenta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CajaDeAhorros.cuenta'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Interes', models.CharField(max_length=30)),
                ('Plazo', models.CharField(max_length=30)),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CajaDeAhorros.cuenta')),
            ],
        ),
    ]
